### ISSUE TITLE
small problem with example crimes data base

### ISSUE THREAD

**Issue by gadamc** [cloudant-labs/spark-cloudant#44] opened 2016-02-24 02:08 UTC
Hey... While going through the 'crimes' database example, I found a problem. It seems that if I want to simply write the 'crimes' database directly back to another cloudant database, I have to .drop('_rev') before I try to save it. 

Here's my example: 
https://gist.github.com/gadamc/6b313e771ed846302c3b

thanks,
Adam

**Comment by HolgerKache** [comment] 2016-02-25 12:33
@gadamc Hi Adam - can you confirm one thing for me, please. Your gist shows that you used 2 different databases to test a) with the _rev in every doc save to `crimes_not_filtered_full_doc and b) without the _rev in every doc save to `crimes_not_filtered_full_doc_droprev.`

The first test returns an error ... _Database crimes_not_filtered_full_doc does not exist or is not accessible. Failed to save data!_ but the second does not? Did you actually create both these databases by hand (both being empty at the point of execution) and still got the above error for a) but not for b)?

I'm trying to understand if the error message is legit and the problem is indeed caused by _rev values. Thanks

**Comment by gadamc** [comment] 2016-03-11 00:51
Hi @HolgerKache. Sorry for the late response. Yes, I created that database in my Cloudant account by hand before I ran the code. I just checked my Cloudant account and that database exists there and the spelling matches.

**Comment by mayya-sharipova** [comment] 2016-03-23 18:55
@gadamc Adam, are you still having this issue,  or if it is resolved can I close this issue?

**Closed** 2016-06-08 22:47 UTC
