### ISSUE TITLE
Job Aborted due to stage failure

### ISSUE THREAD

**Issue by krajaram72** [cloudant-labs/spark-cloudant#27] opened 2016-01-15 20:07 UTC
I have a cloudant database in Bluemix with Twitter data; after creating a dataframe by using this database in Spark while performing a select or filter the job fails with Job Aborted due to stage failure issue.

**Comment by HolgerKache** [comment] 2016-01-18 08:37
To reproduce we can use database: https://f7347f93-fa74-42c8-a4b3-12b5a8aec39d-bluemix.cloudant.com/bmw

The issue is caused by a limitation in our connector code. We describe RDD schema based on the first document we scan. That is not sufficient for the given dataset as some documents don't match the schema of the first document.

Our proposed solution is a new option that allows users to define how many documents should be sampled to derive the correct schema for the RDD. -1 would scan the entire database.

The implementation is underway and tracked internally with BugzId: 59236

**Comment by HolgerKache** [comment] 2016-01-20 10:53
We have made a new release available, v1.6.1 at https://github.com/cloudant-labs/spark-cloudant/releases/tag/v1.6.1

With that release the connector provides an option `schemaSampleSize` that can be used to scan more than 1 document to derive the RDD schema. The option is working as described in the README.md (troubleshooting section)

While the v1.6.1 is available for local Spark clusters today, we have to wait for the Bluemix team to make it available to the Spark Service there. That typically takes a couple of weeks. I will keep this case open until we have pushed v1.6.1 to Bluemix.

**Comment by HolgerKache** [comment] 2016-02-25 12:52
@krajaram72 The v1.6.1 release has been deployed to Bluemix for a couple of weeks now (Feb 10). Your use case works now with the new option as dcoumented here: https://github.com/cloudant-labs/spark-cloudant#schema-variance

To apply the option globally in a Spark notebook on Bluemix, you could just do the following:

```
# kill the default SparkContext already pre-loaded into the JVM
sc.stop()

# define a new one with the schema sample option set to -1
conf = SparkConf().setAppName("Multiple schema test")
conf.set("jsonstore.rdd.schemaSampleSize", -1)

sc = SparkContext(conf=conf)
sqlContext = SQLContext(sc)`
```
After that every RDD schema will be computed based on the entire database you query from Cloudant. Beware that this increases runtime and you may still want to apply the option selectively only. See the documentation for details.

That concludes the work for this ticket. Closing!

**Closed by HolgerKache** 2016-02-25 12:52 UTC

**Comment by krajaram72** [comment] 2016-02-25 14:56
Thanks. It is working for me now!
